INSERT INTO `bateriasmateo`.`consumible` (`tipo`, `id`, `cantidad`, `detalle`, `minimo`, `nombre`) 
VALUES ('I', '1', '800', 'Q8 Formula Truck 8400 FE 5W-30 (en Lts)', '100', '5W-30');

INSERT INTO `bateriasmateo`.`consumible` (`tipo`, `id`, `cantidad`, `detalle`, `minimo`, `nombre`) 
VALUES ('MP', '2', '100000', 'Plomo natural (En Kg)', '6000', 'PLOMO');

INSERT INTO `bateriasmateo`.`consumible` (`tipo`, `id`, `cantidad`, `detalle`, `minimo`, `nombre`) 
VALUES ('PI', '3', '2000', 'Rejillas de Plomo (En unidades)', '10000', 'REJILLAS PLOMO');
