CREATE TABLE IF NOT EXISTS `MATEODEMO`.`MATERIA_PRIMA` (
  `ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `DETALLE` VARCHAR(45) NULL,
  `CANTIDAD` INT NOT NULL DEFAULT 0,
  `VALOR_MINIMO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
  )
